### ISSUE TITLE
Use new mongo drivers instead of outdated.

### ISSUE THREAD

**Issue by alex-erygin** [phoenixwebgroup/DotNetMongoMigrations#18]

**Comment by sergiorykov** [comment]
+1

**Comment by NickAb** [comment]
Use of old mongo leads to exception in ASP.NET Core projects when referencing both MongoMigrations and newer Mongo Driver.
I have non english language as system language

```
System.TypeLoadException: Отсутствует реализация метода "get_ReadConcern" в типе "MongoDB.Driver.MongoServerSettings" из сборки "MongoDB.Driver.Legacy, Version=2.0.1.27, Culture=neutral, PublicKeyToken=null".
```

But basically it reads that get_ReadConcern is not present on MongoDB.Driver.MongoServerSettings in assembly MongoDB.Driver.Legacy, Version=2.0.1.27, Culture=neutral, PublicKeyToken=null

**Comment by denkj** [comment]
I have an error in English.
```
Unhandled Exception: System.TypeLoadException: Method 'get_ReadConcern' in type 'MongoDB.Driver.MongoServerSettings' from assembly 'MongoDB.Driver.Legacy, Version=2.0.1.27, Culture=neutral, PublicKeyToken=null' does not have an implementation.
at MongoDB.Driver.MongoClientExtensions.GetServer(MongoClient client)
at MongoMigrations.MigrationRunner..ctor(String mongoServerLocation, String databaseName)
```

**Comment by jonpaulsalomon** [comment]
Same problem here

**Comment by letitechera** [comment]
Was this fixed??
